 │ │ app/beforeSetup  ERROR in ./resources/assets/js/lib/tutorial.js
 │ │ app/beforeSetup  Module not found: Error: Can't resolve 'intro.js' in                     ↵
 │ │ app/beforeSetup  '/var/www/resources/assets/js/lib'
 │ │ app/beforeSetup   @ ./resources/assets/js/lib/tutorial.js 110:2-52
 │ │ app/beforeSetup   @ ./resources/assets/js/components/game/index.js
 │ │ app/beforeSetup   @ ./resources/assets/js/renderer.js
 │ │ app/beforeSetup   @ ./resources/assets/js/app.js
 │ │ app/beforeSetup   @ multi ./resources/assets/js/app.js
 │ │ app/beforeSetup  npm ERR! code ELIFECYCLE
 │ │ app/beforeSetup  npm ERR! errno 2
 │ │ app/beforeSetup  npm ERR! @ production: `cross-env NODE_ENV=production BUNDLE=all         ↵
 │ │ app/beforeSetup  webpack --progress --hide-modules                                        ↵
 │ │ app/beforeSetup  --config=node_modules/laravel-mix/setup/webpack.config.js`
 │ │ app/beforeSetup  npm ERR! Exit status 2
 │ │ app/beforeSetup  npm ERR! 
 │ │ app/beforeSetup  npm ERR! Failed at the @ production script.
 │ │ app/beforeSetup  npm ERR! This is probably not a problem with npm. There is likely        ↵
 │ │ app/beforeSetup  additional logging output above.
 │ │ app/beforeSetup  
 │ │ app/beforeSetup  npm ERR! A complete log of this run can be found in:
 │ │ app/beforeSetup  npm ERR!     /root/.npm/_logs/2020-10-13T14_33_17_953Z-debug.log


??????????????WTF????????????
